server:
  port: 8082
spring:
  datasource:
    url: jdbc:h2:mem:words
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console.enabled: true